// Copyright 2026 The Autoware Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The estimation logic of this file is a port of LIO-SAM's
// src/imuPreintegration.cpp (IMUPreintegration class), which is distributed by
// Tixiao Shan under the BSD-3-Clause license; see
// src/universe/external/LIO-SAM/LICENSE for the full text.
//
// Changes: the ROS wiring is replaced by the FusionPlugin interface, and the
// output covariance is generated by the joint 15x15 propagation of design
// section 5.2.1 (D39) because the original publishes no pose covariance at all.

#ifndef PLUGINS__LIO_SAM__LIO_SAM_IMU_PREINTEGRATION_PLUGIN_HPP_
#define PLUGINS__LIO_SAM__LIO_SAM_IMU_PREINTEGRATION_PLUGIN_HPP_

#include "autoware/pose_twist_fusion/fusion_plugin_base.hpp"
#include "plugins/lio_sam/lio_sam_covariance.hpp"

#include <gtsam/navigation/ImuFactor.h>
#include <gtsam/nonlinear/ISAM2.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/Values.h>

#include <deque>
#include <memory>
#include <mutex>

namespace autoware::pose_twist_fusion
{

class LioSamImuPreintegrationPlugin : public FusionPlugin
{
public:
  void initialize(rclcpp::Node & node, const Parameters & params) override;
  [[nodiscard]] InputRequirements required_inputs() const override;
  void on_imu(const sensor_msgs::msg::Imu & msg) override;
  void on_slam_odometry(const nav_msgs::msg::Odometry & msg) override;
  void reset() override;
  [[nodiscard]] InternalEstimate estimate_internal(const rclcpp::Time & stamp) const override;
  [[nodiscard]] std::optional<InternalEstimate> estimate_internal_previous(
    const rclcpp::Time & stamp) const override;
  [[nodiscard]] EstimateGeneration generation() const override;
  [[nodiscard]] diagnostic_msgs::msg::DiagnosticStatus diagnostics() const override;
  [[nodiscard]] bool is_running() const override;

private:
  /// Anchor + integrator pair. Two of them are kept alive (current / previous) so
  /// that OutputStage can evaluate both generations at the same instant (D37).
  struct Snapshot
  {
    gtsam::NavState state;
    gtsam::imuBias::ConstantBias bias;
    std::shared_ptr<gtsam::PreintegratedImuMeasurements> pim;
    double anchor_time{0.0};
    lio_sam::Matrix15 covariance{lio_sam::Matrix15::Identity()};
    double last_imu_time{0.0};
    gtsam::Vector3 last_gyro{gtsam::Vector3::Zero()};
    gtsam::Vector3 last_accel{gtsam::Vector3::Zero()};
  };

  void reset_optimization();
  void reset_params();
  bool failure_detection(
    const gtsam::Vector3 & velocity, const gtsam::imuBias::ConstantBias & bias) const;
  InternalEstimate evaluate(const Snapshot & snapshot, double stamp) const;
  lio_sam::Matrix15 anchor_covariance(const gtsam::Values & result, std::uint64_t key) const;

  rclcpp::Node * node_{nullptr};
  Parameters params_;
  gtsam::Pose3 t_base_imu_;  // base_link <- imu_link

  mutable std::mutex mutex_;
  gtsam::ISAM2 optimizer_;
  gtsam::NonlinearFactorGraph graph_factors_;
  gtsam::Values graph_values_;

  gtsam::noiseModel::Diagonal::shared_ptr prior_pose_noise_;
  gtsam::noiseModel::Isotropic::shared_ptr prior_vel_noise_;
  gtsam::noiseModel::Isotropic::shared_ptr prior_bias_noise_;
  gtsam::noiseModel::Diagonal::shared_ptr correction_noise_;
  gtsam::noiseModel::Diagonal::shared_ptr correction_noise2_;
  gtsam::Vector6 noise_model_between_bias_;

  boost::shared_ptr<gtsam::PreintegrationParams> preint_params_;
  std::shared_ptr<gtsam::PreintegratedImuMeasurements> imu_integrator_opt_;

  std::deque<sensor_msgs::msg::Imu> imu_que_opt_;
  std::deque<sensor_msgs::msg::Imu> imu_que_imu_;

  gtsam::Pose3 prev_pose_;
  gtsam::Vector3 prev_vel_{gtsam::Vector3::Zero()};
  gtsam::NavState prev_state_;
  gtsam::imuBias::ConstantBias prev_bias_;

  std::shared_ptr<Snapshot> current_;
  std::shared_ptr<Snapshot> previous_;

  std::uint64_t key_{1};
  bool system_initialized_{false};
  bool done_first_opt_{false};
  double last_imu_t_opt_{-1.0};
  double last_odometry_time_{0.0};
  EstimateGeneration generation_{0};
  std::uint64_t failure_count_{0};
  bool marginals_failed_{false};
};

}  // namespace autoware::pose_twist_fusion

#endif  // PLUGINS__LIO_SAM__LIO_SAM_IMU_PREINTEGRATION_PLUGIN_HPP_
